/* ============================================================================
   brain_data.js  -  the SEED concept-brain for brain.html (clozn flagship viz)
   ----------------------------------------------------------------------------
   A representative, hand-shaped mind: 12 semantic LOBES (clusters), evocative
   concept nodes, dense intra-lobe synapses + sparse cross-lobe bridges chosen to
   read like real associations (fear<->memory, light<->emotion, sound<->language).
   This is DEMO data. To show a real model, export SAE-feature co-activation /
   cosine-similarity to this EXACT shape and import it instead (see brain_README.md):

     clusters: [{ id, label, color }]               // a glowing lobe
     nodes:    [{ id, label, cluster, value }]      // value 0..1 = activation/importance
     links:    [{ source, target, weight }]         // weight 0..1 = association strength
   ============================================================================ */
export const BRAIN = {
  clusters: [{"id": "light", "label": "Light", "color": "#36AEC4"}, {"id": "sound", "label": "Sound", "color": "#4C8DF0"}, {"id": "motion", "label": "Motion", "color": "#3F9BD6"}, {"id": "time", "label": "Time", "color": "#5E6E9E"}, {"id": "measurement", "label": "Measurement", "color": "#677591"}, {"id": "logic_code", "label": "Logic & Code", "color": "#2FA86A"}, {"id": "language", "label": "Language", "color": "#7C8AB8"}, {"id": "memory", "label": "Memory", "color": "#8B79E8"}, {"id": "emotion", "label": "Emotion", "color": "#CE64DE"}, {"id": "fear", "label": "Fear", "color": "#9A6CC9"}, {"id": "body", "label": "Body", "color": "#C68A1E"}, {"id": "myth", "label": "Myth & Fantasy", "color": "#46B0A6"}],
  nodes: [
    {"id": "light:photon", "label": "photon", "cluster": "light", "value": 0.271},
    {"id": "light:glow", "label": "glow", "cluster": "light", "value": 0.734},
    {"id": "light:dawn", "label": "dawn", "cluster": "light", "value": 0.287},
    {"id": "light:shimmer", "label": "shimmer", "cluster": "light", "value": 0.599},
    {"id": "light:prism", "label": "prism", "cluster": "light", "value": 0.458},
    {"id": "light:shadow", "label": "shadow", "cluster": "light", "value": 0.734},
    {"id": "light:halo", "label": "halo", "cluster": "light", "value": 0.2},
    {"id": "light:ember", "label": "ember", "cluster": "light", "value": 0.736},
    {"id": "light:starlight", "label": "starlight", "cluster": "light", "value": 0.61},
    {"id": "light:lantern", "label": "lantern", "cluster": "light", "value": 0.266},
    {"id": "light:gleam", "label": "gleam", "cluster": "light", "value": 0.275},
    {"id": "light:dusk", "label": "dusk", "cluster": "light", "value": 0.593},
    {"id": "light:aurora", "label": "aurora", "cluster": "light", "value": 0.547},
    {"id": "light:candle", "label": "candle", "cluster": "light", "value": 0.49},
    {"id": "light:radiance", "label": "radiance", "cluster": "light", "value": 0.738},
    {"id": "light:eclipse", "label": "eclipse", "cluster": "light", "value": 0.702},
    {"id": "light:flicker", "label": "flicker", "cluster": "light", "value": 0.556},
    {"id": "sound:echo", "label": "echo", "cluster": "sound", "value": 0.685},
    {"id": "sound:whisper", "label": "whisper", "cluster": "sound", "value": 0.277},
    {"id": "sound:thunder", "label": "thunder", "cluster": "sound", "value": 0.631},
    {"id": "sound:melody", "label": "melody", "cluster": "sound", "value": 0.293},
    {"id": "sound:silence", "label": "silence", "cluster": "sound", "value": 0.765},
    {"id": "sound:hum", "label": "hum", "cluster": "sound", "value": 0.351},
    {"id": "sound:chime", "label": "chime", "cluster": "sound", "value": 0.912},
    {"id": "sound:resonance", "label": "resonance", "cluster": "sound", "value": 0.348},
    {"id": "sound:rhythm", "label": "rhythm", "cluster": "sound", "value": 0.503},
    {"id": "sound:murmur", "label": "murmur", "cluster": "sound", "value": 0.603},
    {"id": "sound:drumbeat", "label": "drumbeat", "cluster": "sound", "value": 0.324},
    {"id": "sound:harmony", "label": "harmony", "cluster": "sound", "value": 0.534},
    {"id": "sound:ringing", "label": "ringing", "cluster": "sound", "value": 0.605},
    {"id": "sound:static", "label": "static", "cluster": "sound", "value": 0.2},
    {"id": "sound:lullaby", "label": "lullaby", "cluster": "sound", "value": 0.662},
    {"id": "sound:crescendo", "label": "crescendo", "cluster": "sound", "value": 0.733},
    {"id": "motion:drift", "label": "drift", "cluster": "motion", "value": 0.419},
    {"id": "motion:fall", "label": "fall", "cluster": "motion", "value": 0.722},
    {"id": "motion:spiral", "label": "spiral", "cluster": "motion", "value": 0.461},
    {"id": "motion:tremor", "label": "tremor", "cluster": "motion", "value": 0.519},
    {"id": "motion:glide", "label": "glide", "cluster": "motion", "value": 0.79},
    {"id": "motion:collapse", "label": "collapse", "cluster": "motion", "value": 0.742},
    {"id": "motion:orbit", "label": "orbit", "cluster": "motion", "value": 0.722},
    {"id": "motion:sway", "label": "sway", "cluster": "motion", "value": 0.12},
    {"id": "motion:plunge", "label": "plunge", "cluster": "motion", "value": 0.41},
    {"id": "motion:ripple", "label": "ripple", "cluster": "motion", "value": 0.315},
    {"id": "motion:rush", "label": "rush", "cluster": "motion", "value": 0.75},
    {"id": "motion:stillness", "label": "stillness", "cluster": "motion", "value": 0.725},
    {"id": "motion:spin", "label": "spin", "cluster": "motion", "value": 0.375},
    {"id": "motion:tumble", "label": "tumble", "cluster": "motion", "value": 0.746},
    {"id": "motion:ascent", "label": "ascent", "cluster": "motion", "value": 0.846},
    {"id": "motion:velocity", "label": "velocity", "cluster": "motion", "value": 0.333},
    {"id": "motion:gesture", "label": "gesture", "cluster": "motion", "value": 0.508},
    {"id": "time:instant", "label": "instant", "cluster": "time", "value": 0.386},
    {"id": "time:aeon", "label": "aeon", "cluster": "time", "value": 0.722},
    {"id": "time:yesterday", "label": "yesterday", "cluster": "time", "value": 0.504},
    {"id": "time:forever", "label": "forever", "cluster": "time", "value": 0.414},
    {"id": "time:decay", "label": "decay", "cluster": "time", "value": 0.884},
    {"id": "time:dawn-of", "label": "dawn-of", "cluster": "time", "value": 0.169},
    {"id": "time:clockwork", "label": "clockwork", "cluster": "time", "value": 0.309},
    {"id": "time:fleeting", "label": "fleeting", "cluster": "time", "value": 0.275},
    {"id": "time:anniversary", "label": "anniversary", "cluster": "time", "value": 0.56},
    {"id": "time:epoch", "label": "epoch", "cluster": "time", "value": 0.479},
    {"id": "time:tomorrow", "label": "tomorrow", "cluster": "time", "value": 0.407},
    {"id": "time:hourglass", "label": "hourglass", "cluster": "time", "value": 0.51},
    {"id": "time:cycle", "label": "cycle", "cluster": "time", "value": 0.796},
    {"id": "time:ancient", "label": "ancient", "cluster": "time", "value": 0.12},
    {"id": "time:sudden", "label": "sudden", "cluster": "time", "value": 0.178},
    {"id": "time:wait", "label": "wait", "cluster": "time", "value": 0.794},
    {"id": "measurement:weight", "label": "weight", "cluster": "measurement", "value": 0.551},
    {"id": "measurement:distance", "label": "distance", "cluster": "measurement", "value": 0.588},
    {"id": "measurement:threshold", "label": "threshold", "cluster": "measurement", "value": 0.831},
    {"id": "measurement:ratio", "label": "ratio", "cluster": "measurement", "value": 0.762},
    {"id": "measurement:precision", "label": "precision", "cluster": "measurement", "value": 0.796},
    {"id": "measurement:scale", "label": "scale", "cluster": "measurement", "value": 0.169},
    {"id": "measurement:tally", "label": "tally", "cluster": "measurement", "value": 0.574},
    {"id": "measurement:margin", "label": "margin", "cluster": "measurement", "value": 0.707},
    {"id": "measurement:gradient", "label": "gradient", "cluster": "measurement", "value": 0.779},
    {"id": "measurement:unit", "label": "unit", "cluster": "measurement", "value": 0.742},
    {"id": "measurement:calibrate", "label": "calibrate", "cluster": "measurement", "value": 0.16},
    {"id": "measurement:span", "label": "span", "cluster": "measurement", "value": 0.845},
    {"id": "measurement:density", "label": "density", "cluster": "measurement", "value": 0.665},
    {"id": "measurement:fraction", "label": "fraction", "cluster": "measurement", "value": 0.175},
    {"id": "measurement:tolerance", "label": "tolerance", "cluster": "measurement", "value": 0.578},
    {"id": "measurement:count", "label": "count", "cluster": "measurement", "value": 0.72},
    {"id": "logic_code:recursion", "label": "recursion", "cluster": "logic_code", "value": 0.145},
    {"id": "logic_code:truth", "label": "truth", "cluster": "logic_code", "value": 0.468},
    {"id": "logic_code:loop", "label": "loop", "cluster": "logic_code", "value": 0.86},
    {"id": "logic_code:paradox", "label": "paradox", "cluster": "logic_code", "value": 0.584},
    {"id": "logic_code:function", "label": "function", "cluster": "logic_code", "value": 0.33},
    {"id": "logic_code:null", "label": "null", "cluster": "logic_code", "value": 0.838},
    {"id": "logic_code:branch", "label": "branch", "cluster": "logic_code", "value": 0.758},
    {"id": "logic_code:proof", "label": "proof", "cluster": "logic_code", "value": 0.491},
    {"id": "logic_code:syntax", "label": "syntax", "cluster": "logic_code", "value": 0.41},
    {"id": "logic_code:invariant", "label": "invariant", "cluster": "logic_code", "value": 0.332},
    {"id": "logic_code:cache", "label": "cache", "cluster": "logic_code", "value": 0.494},
    {"id": "logic_code:boolean", "label": "boolean", "cluster": "logic_code", "value": 0.286},
    {"id": "logic_code:pointer", "label": "pointer", "cluster": "logic_code", "value": 0.468},
    {"id": "logic_code:grammar-of", "label": "grammar-of", "cluster": "logic_code", "value": 0.272},
    {"id": "logic_code:stack", "label": "stack", "cluster": "logic_code", "value": 0.12},
    {"id": "logic_code:entropy", "label": "entropy", "cluster": "logic_code", "value": 0.742},
    {"id": "language:metaphor", "label": "metaphor", "cluster": "language", "value": 0.282},
    {"id": "language:verb", "label": "verb", "cluster": "language", "value": 0.385},
    {"id": "language:silence-of", "label": "silence-of", "cluster": "language", "value": 0.409},
    {"id": "language:syllable", "label": "syllable", "cluster": "language", "value": 0.398},
    {"id": "language:name", "label": "name", "cluster": "language", "value": 0.732},
    {"id": "language:translate", "label": "translate", "cluster": "language", "value": 0.762},
    {"id": "language:whisper-word", "label": "whisper-word", "cluster": "language", "value": 0.798},
    {"id": "language:paragraph", "label": "paragraph", "cluster": "language", "value": 0.44},
    {"id": "language:idiom", "label": "idiom", "cluster": "language", "value": 0.429},
    {"id": "language:question", "label": "question", "cluster": "language", "value": 0.518},
    {"id": "language:accent", "label": "accent", "cluster": "language", "value": 0.15},
    {"id": "language:grammar", "label": "grammar", "cluster": "language", "value": 0.743},
    {"id": "language:story", "label": "story", "cluster": "language", "value": 0.438},
    {"id": "language:meaning", "label": "meaning", "cluster": "language", "value": 0.447},
    {"id": "language:stammer", "label": "stammer", "cluster": "language", "value": 0.12},
    {"id": "memory:recall", "label": "recall", "cluster": "memory", "value": 0.543},
    {"id": "memory:forgetting", "label": "forgetting", "cluster": "memory", "value": 0.445},
    {"id": "memory:nostalgia", "label": "nostalgia", "cluster": "memory", "value": 0.78},
    {"id": "memory:trace", "label": "trace", "cluster": "memory", "value": 0.282},
    {"id": "memory:imprint", "label": "imprint", "cluster": "memory", "value": 0.12},
    {"id": "memory:deja-vu", "label": "deja-vu", "cluster": "memory", "value": 0.28},
    {"id": "memory:keepsake", "label": "keepsake", "cluster": "memory", "value": 0.12},
    {"id": "memory:fading", "label": "fading", "cluster": "memory", "value": 0.453},
    {"id": "memory:remembrance", "label": "remembrance", "cluster": "memory", "value": 0.721},
    {"id": "memory:echo-of", "label": "echo-of", "cluster": "memory", "value": 0.283},
    {"id": "memory:childhood", "label": "childhood", "cluster": "memory", "value": 0.182},
    {"id": "memory:relic", "label": "relic", "cluster": "memory", "value": 0.385},
    {"id": "memory:reminisce", "label": "reminisce", "cluster": "memory", "value": 0.669},
    {"id": "memory:palimpsest", "label": "palimpsest", "cluster": "memory", "value": 0.503},
    {"id": "memory:scar-of", "label": "scar-of", "cluster": "memory", "value": 0.484},
    {"id": "emotion:longing", "label": "longing", "cluster": "emotion", "value": 0.358},
    {"id": "emotion:joy", "label": "joy", "cluster": "emotion", "value": 0.704},
    {"id": "emotion:grief", "label": "grief", "cluster": "emotion", "value": 0.842},
    {"id": "emotion:tenderness", "label": "tenderness", "cluster": "emotion", "value": 0.463},
    {"id": "emotion:awe", "label": "awe", "cluster": "emotion", "value": 0.343},
    {"id": "emotion:yearning", "label": "yearning", "cluster": "emotion", "value": 0.432},
    {"id": "emotion:serenity", "label": "serenity", "cluster": "emotion", "value": 0.143},
    {"id": "emotion:ache", "label": "ache", "cluster": "emotion", "value": 0.34},
    {"id": "emotion:wonder", "label": "wonder", "cluster": "emotion", "value": 0.124},
    {"id": "emotion:melancholy", "label": "melancholy", "cluster": "emotion", "value": 0.813},
    {"id": "emotion:elation", "label": "elation", "cluster": "emotion", "value": 0.37},
    {"id": "emotion:comfort", "label": "comfort", "cluster": "emotion", "value": 0.736},
    {"id": "emotion:sorrow", "label": "sorrow", "cluster": "emotion", "value": 0.227},
    {"id": "emotion:delight", "label": "delight", "cluster": "emotion", "value": 0.168},
    {"id": "emotion:reverence", "label": "reverence", "cluster": "emotion", "value": 0.186},
    {"id": "fear:dread", "label": "dread", "cluster": "fear", "value": 0.455},
    {"id": "fear:panic", "label": "panic", "cluster": "fear", "value": 0.763},
    {"id": "fear:trembling", "label": "trembling", "cluster": "fear", "value": 0.458},
    {"id": "fear:abyss", "label": "abyss", "cluster": "fear", "value": 0.649},
    {"id": "fear:nightmare", "label": "nightmare", "cluster": "fear", "value": 0.266},
    {"id": "fear:lurking", "label": "lurking", "cluster": "fear", "value": 0.604},
    {"id": "fear:unease", "label": "unease", "cluster": "fear", "value": 0.762},
    {"id": "fear:flinch", "label": "flinch", "cluster": "fear", "value": 0.559},
    {"id": "fear:darkness-of", "label": "darkness-of", "cluster": "fear", "value": 0.701},
    {"id": "fear:threat", "label": "threat", "cluster": "fear", "value": 0.447},
    {"id": "fear:cold-sweat", "label": "cold-sweat", "cluster": "fear", "value": 0.12},
    {"id": "fear:vertigo", "label": "vertigo", "cluster": "fear", "value": 0.711},
    {"id": "fear:foreboding", "label": "foreboding", "cluster": "fear", "value": 0.572},
    {"id": "fear:startle", "label": "startle", "cluster": "fear", "value": 0.364},
    {"id": "fear:helpless", "label": "helpless", "cluster": "fear", "value": 0.863},
    {"id": "body:heartbeat", "label": "heartbeat", "cluster": "body", "value": 0.512},
    {"id": "body:breath", "label": "breath", "cluster": "body", "value": 0.271},
    {"id": "body:skin", "label": "skin", "cluster": "body", "value": 0.448},
    {"id": "body:pulse", "label": "pulse", "cluster": "body", "value": 0.854},
    {"id": "body:muscle", "label": "muscle", "cluster": "body", "value": 0.12},
    {"id": "body:fingertip", "label": "fingertip", "cluster": "body", "value": 0.393},
    {"id": "body:spine", "label": "spine", "cluster": "body", "value": 0.441},
    {"id": "body:ache-of", "label": "ache-of", "cluster": "body", "value": 0.566},
    {"id": "body:warmth", "label": "warmth", "cluster": "body", "value": 0.36},
    {"id": "body:hunger", "label": "hunger", "cluster": "body", "value": 0.142},
    {"id": "body:nerve", "label": "nerve", "cluster": "body", "value": 0.776},
    {"id": "body:blood", "label": "blood", "cluster": "body", "value": 0.127},
    {"id": "body:flush", "label": "flush", "cluster": "body", "value": 0.714},
    {"id": "body:shiver", "label": "shiver", "cluster": "body", "value": 0.494},
    {"id": "body:exhale", "label": "exhale", "cluster": "body", "value": 0.348},
    {"id": "body:sinew", "label": "sinew", "cluster": "body", "value": 0.805},
    {"id": "myth:angel", "label": "angel", "cluster": "myth", "value": 0.512},
    {"id": "myth:oracle", "label": "oracle", "cluster": "myth", "value": 0.281},
    {"id": "myth:leviathan", "label": "leviathan", "cluster": "myth", "value": 0.248},
    {"id": "myth:threshold-god", "label": "threshold-god", "cluster": "myth", "value": 0.243},
    {"id": "myth:phoenix", "label": "phoenix", "cluster": "myth", "value": 0.724},
    {"id": "myth:labyrinth", "label": "labyrinth", "cluster": "myth", "value": 0.451},
    {"id": "myth:prophecy", "label": "prophecy", "cluster": "myth", "value": 0.715},
    {"id": "myth:relic-of", "label": "relic-of", "cluster": "myth", "value": 0.12},
    {"id": "myth:seraph", "label": "seraph", "cluster": "myth", "value": 0.207},
    {"id": "myth:underworld", "label": "underworld", "cluster": "myth", "value": 0.171},
    {"id": "myth:dragon", "label": "dragon", "cluster": "myth", "value": 0.675},
    {"id": "myth:talisman", "label": "talisman", "cluster": "myth", "value": 0.464},
    {"id": "myth:ascension", "label": "ascension", "cluster": "myth", "value": 0.383},
    {"id": "myth:omen", "label": "omen", "cluster": "myth", "value": 0.72},
    {"id": "myth:chimera", "label": "chimera", "cluster": "myth", "value": 0.925},
    {"id": "myth:halo-of", "label": "halo-of", "cluster": "myth", "value": 0.424},
  ],
  links: [
    {"source": "light:gleam", "target": "light:dusk", "weight": 0.823},
    {"source": "light:dusk", "target": "light:candle", "weight": 0.532},
    {"source": "light:candle", "target": "light:shimmer", "weight": 0.548},
    {"source": "light:shimmer", "target": "light:flicker", "weight": 0.63},
    {"source": "light:flicker", "target": "light:starlight", "weight": 0.683},
    {"source": "light:starlight", "target": "light:aurora", "weight": 0.623},
    {"source": "light:aurora", "target": "light:dawn", "weight": 0.505},
    {"source": "light:dawn", "target": "light:eclipse", "weight": 0.561},
    {"source": "light:eclipse", "target": "light:halo", "weight": 0.776},
    {"source": "light:halo", "target": "light:lantern", "weight": 0.854},
    {"source": "light:lantern", "target": "light:photon", "weight": 0.468},
    {"source": "light:photon", "target": "light:shadow", "weight": 0.703},
    {"source": "light:shadow", "target": "light:ember", "weight": 0.791},
    {"source": "light:ember", "target": "light:radiance", "weight": 0.467},
    {"source": "light:radiance", "target": "light:glow", "weight": 0.827},
    {"source": "light:glow", "target": "light:prism", "weight": 0.503},
    {"source": "light:prism", "target": "light:gleam", "weight": 0.72},
    {"source": "light:halo", "target": "light:ember", "weight": 0.47},
    {"source": "light:dawn", "target": "light:ember", "weight": 0.514},
    {"source": "light:photon", "target": "light:radiance", "weight": 0.577},
    {"source": "light:starlight", "target": "light:gleam", "weight": 0.302},
    {"source": "light:radiance", "target": "light:starlight", "weight": 0.746},
    {"source": "light:shadow", "target": "light:shimmer", "weight": 0.337},
    {"source": "light:photon", "target": "light:ember", "weight": 0.501},
    {"source": "light:radiance", "target": "light:dusk", "weight": 0.322},
    {"source": "light:flicker", "target": "light:candle", "weight": 0.807},
    {"source": "light:lantern", "target": "light:candle", "weight": 0.33},
    {"source": "light:prism", "target": "light:shadow", "weight": 0.659},
    {"source": "light:flicker", "target": "light:gleam", "weight": 0.771},
    {"source": "light:shimmer", "target": "light:aurora", "weight": 0.372},
    {"source": "light:glow", "target": "light:halo", "weight": 0.826},
    {"source": "light:starlight", "target": "light:dawn", "weight": 0.336},
    {"source": "light:photon", "target": "light:eclipse", "weight": 0.387},
    {"source": "light:eclipse", "target": "light:radiance", "weight": 0.379},
    {"source": "light:dusk", "target": "light:aurora", "weight": 0.4},
    {"source": "light:starlight", "target": "light:eclipse", "weight": 0.674},
    {"source": "light:shadow", "target": "light:starlight", "weight": 0.736},
    {"source": "light:eclipse", "target": "light:shimmer", "weight": 0.723},
    {"source": "light:dusk", "target": "light:photon", "weight": 0.831},
    {"source": "sound:ringing", "target": "sound:echo", "weight": 0.612},
    {"source": "sound:echo", "target": "sound:drumbeat", "weight": 0.794},
    {"source": "sound:drumbeat", "target": "sound:melody", "weight": 0.649},
    {"source": "sound:melody", "target": "sound:resonance", "weight": 0.53},
    {"source": "sound:resonance", "target": "sound:thunder", "weight": 0.785},
    {"source": "sound:thunder", "target": "sound:hum", "weight": 0.472},
    {"source": "sound:hum", "target": "sound:chime", "weight": 0.819},
    {"source": "sound:chime", "target": "sound:static", "weight": 0.564},
    {"source": "sound:static", "target": "sound:silence", "weight": 0.738},
    {"source": "sound:silence", "target": "sound:whisper", "weight": 0.893},
    {"source": "sound:whisper", "target": "sound:harmony", "weight": 0.714},
    {"source": "sound:harmony", "target": "sound:murmur", "weight": 0.749},
    {"source": "sound:murmur", "target": "sound:crescendo", "weight": 0.591},
    {"source": "sound:crescendo", "target": "sound:rhythm", "weight": 0.451},
    {"source": "sound:rhythm", "target": "sound:lullaby", "weight": 0.465},
    {"source": "sound:lullaby", "target": "sound:ringing", "weight": 0.517},
    {"source": "sound:crescendo", "target": "sound:hum", "weight": 0.582},
    {"source": "sound:harmony", "target": "sound:resonance", "weight": 0.358},
    {"source": "sound:harmony", "target": "sound:static", "weight": 0.423},
    {"source": "sound:silence", "target": "sound:lullaby", "weight": 0.374},
    {"source": "sound:harmony", "target": "sound:silence", "weight": 0.756},
    {"source": "sound:thunder", "target": "sound:drumbeat", "weight": 0.308},
    {"source": "sound:chime", "target": "sound:harmony", "weight": 0.382},
    {"source": "sound:melody", "target": "sound:echo", "weight": 0.651},
    {"source": "sound:static", "target": "sound:hum", "weight": 0.746},
    {"source": "sound:rhythm", "target": "sound:silence", "weight": 0.815},
    {"source": "sound:lullaby", "target": "sound:melody", "weight": 0.391},
    {"source": "sound:ringing", "target": "sound:hum", "weight": 0.402},
    {"source": "sound:thunder", "target": "sound:ringing", "weight": 0.801},
    {"source": "sound:melody", "target": "sound:ringing", "weight": 0.637},
    {"source": "sound:hum", "target": "sound:drumbeat", "weight": 0.527},
    {"source": "sound:crescendo", "target": "sound:lullaby", "weight": 0.637},
    {"source": "sound:silence", "target": "sound:echo", "weight": 0.465},
    {"source": "sound:echo", "target": "sound:rhythm", "weight": 0.698},
    {"source": "sound:lullaby", "target": "sound:harmony", "weight": 0.596},
    {"source": "motion:collapse", "target": "motion:glide", "weight": 0.851},
    {"source": "motion:glide", "target": "motion:ripple", "weight": 0.866},
    {"source": "motion:ripple", "target": "motion:orbit", "weight": 0.874},
    {"source": "motion:orbit", "target": "motion:gesture", "weight": 0.568},
    {"source": "motion:gesture", "target": "motion:plunge", "weight": 0.474},
    {"source": "motion:plunge", "target": "motion:drift", "weight": 0.736},
    {"source": "motion:drift", "target": "motion:tremor", "weight": 0.756},
    {"source": "motion:tremor", "target": "motion:spiral", "weight": 0.759},
    {"source": "motion:spiral", "target": "motion:velocity", "weight": 0.863},
    {"source": "motion:velocity", "target": "motion:rush", "weight": 0.887},
    {"source": "motion:rush", "target": "motion:ascent", "weight": 0.583},
    {"source": "motion:ascent", "target": "motion:fall", "weight": 0.868},
    {"source": "motion:fall", "target": "motion:sway", "weight": 0.852},
    {"source": "motion:sway", "target": "motion:stillness", "weight": 0.488},
    {"source": "motion:stillness", "target": "motion:tumble", "weight": 0.678},
    {"source": "motion:tumble", "target": "motion:spin", "weight": 0.526},
    {"source": "motion:spin", "target": "motion:collapse", "weight": 0.857},
    {"source": "motion:rush", "target": "motion:drift", "weight": 0.784},
    {"source": "motion:rush", "target": "motion:tremor", "weight": 0.509},
    {"source": "motion:tremor", "target": "motion:velocity", "weight": 0.734},
    {"source": "motion:fall", "target": "motion:ripple", "weight": 0.611},
    {"source": "motion:orbit", "target": "motion:spin", "weight": 0.642},
    {"source": "motion:plunge", "target": "motion:ascent", "weight": 0.838},
    {"source": "motion:ripple", "target": "motion:ascent", "weight": 0.41},
    {"source": "motion:drift", "target": "motion:spin", "weight": 0.362},
    {"source": "motion:velocity", "target": "motion:tumble", "weight": 0.355},
    {"source": "motion:orbit", "target": "motion:drift", "weight": 0.462},
    {"source": "motion:rush", "target": "motion:sway", "weight": 0.444},
    {"source": "motion:ascent", "target": "motion:spiral", "weight": 0.812},
    {"source": "motion:glide", "target": "motion:ascent", "weight": 0.801},
    {"source": "motion:collapse", "target": "motion:sway", "weight": 0.317},
    {"source": "motion:glide", "target": "motion:drift", "weight": 0.693},
    {"source": "time:fleeting", "target": "time:cycle", "weight": 0.671},
    {"source": "time:cycle", "target": "time:aeon", "weight": 0.809},
    {"source": "time:aeon", "target": "time:tomorrow", "weight": 0.533},
    {"source": "time:tomorrow", "target": "time:dawn-of", "weight": 0.673},
    {"source": "time:dawn-of", "target": "time:sudden", "weight": 0.606},
    {"source": "time:sudden", "target": "time:hourglass", "weight": 0.824},
    {"source": "time:hourglass", "target": "time:forever", "weight": 0.567},
    {"source": "time:forever", "target": "time:anniversary", "weight": 0.875},
    {"source": "time:anniversary", "target": "time:instant", "weight": 0.578},
    {"source": "time:instant", "target": "time:clockwork", "weight": 0.547},
    {"source": "time:clockwork", "target": "time:wait", "weight": 0.765},
    {"source": "time:wait", "target": "time:decay", "weight": 0.674},
    {"source": "time:decay", "target": "time:ancient", "weight": 0.499},
    {"source": "time:ancient", "target": "time:epoch", "weight": 0.736},
    {"source": "time:epoch", "target": "time:yesterday", "weight": 0.486},
    {"source": "time:yesterday", "target": "time:fleeting", "weight": 0.805},
    {"source": "time:tomorrow", "target": "time:clockwork", "weight": 0.48},
    {"source": "time:tomorrow", "target": "time:hourglass", "weight": 0.811},
    {"source": "time:aeon", "target": "time:hourglass", "weight": 0.789},
    {"source": "time:fleeting", "target": "time:sudden", "weight": 0.413},
    {"source": "time:anniversary", "target": "time:hourglass", "weight": 0.796},
    {"source": "time:forever", "target": "time:yesterday", "weight": 0.37},
    {"source": "time:cycle", "target": "time:sudden", "weight": 0.62},
    {"source": "time:dawn-of", "target": "time:ancient", "weight": 0.764},
    {"source": "time:clockwork", "target": "time:aeon", "weight": 0.555},
    {"source": "time:clockwork", "target": "time:forever", "weight": 0.653},
    {"source": "time:instant", "target": "time:decay", "weight": 0.687},
    {"source": "time:dawn-of", "target": "time:wait", "weight": 0.386},
    {"source": "time:forever", "target": "time:wait", "weight": 0.48},
    {"source": "time:wait", "target": "time:aeon", "weight": 0.43},
    {"source": "time:hourglass", "target": "time:dawn-of", "weight": 0.836},
    {"source": "time:tomorrow", "target": "time:yesterday", "weight": 0.511},
    {"source": "time:dawn-of", "target": "time:decay", "weight": 0.466},
    {"source": "time:instant", "target": "time:hourglass", "weight": 0.451},
    {"source": "time:anniversary", "target": "time:tomorrow", "weight": 0.787},
    {"source": "measurement:scale", "target": "measurement:unit", "weight": 0.859},
    {"source": "measurement:unit", "target": "measurement:span", "weight": 0.644},
    {"source": "measurement:span", "target": "measurement:calibrate", "weight": 0.708},
    {"source": "measurement:calibrate", "target": "measurement:threshold", "weight": 0.787},
    {"source": "measurement:threshold", "target": "measurement:distance", "weight": 0.64},
    {"source": "measurement:distance", "target": "measurement:fraction", "weight": 0.553},
    {"source": "measurement:fraction", "target": "measurement:margin", "weight": 0.775},
    {"source": "measurement:margin", "target": "measurement:precision", "weight": 0.846},
    {"source": "measurement:precision", "target": "measurement:gradient", "weight": 0.798},
    {"source": "measurement:gradient", "target": "measurement:ratio", "weight": 0.765},
    {"source": "measurement:ratio", "target": "measurement:density", "weight": 0.834},
    {"source": "measurement:density", "target": "measurement:tally", "weight": 0.756},
    {"source": "measurement:tally", "target": "measurement:count", "weight": 0.739},
    {"source": "measurement:count", "target": "measurement:weight", "weight": 0.654},
    {"source": "measurement:weight", "target": "measurement:tolerance", "weight": 0.591},
    {"source": "measurement:tolerance", "target": "measurement:scale", "weight": 0.733},
    {"source": "measurement:calibrate", "target": "measurement:weight", "weight": 0.531},
    {"source": "measurement:tolerance", "target": "measurement:margin", "weight": 0.311},
    {"source": "measurement:count", "target": "measurement:precision", "weight": 0.671},
    {"source": "measurement:distance", "target": "measurement:weight", "weight": 0.66},
    {"source": "measurement:scale", "target": "measurement:fraction", "weight": 0.758},
    {"source": "measurement:calibrate", "target": "measurement:scale", "weight": 0.438},
    {"source": "measurement:fraction", "target": "measurement:span", "weight": 0.694},
    {"source": "measurement:fraction", "target": "measurement:precision", "weight": 0.492},
    {"source": "measurement:weight", "target": "measurement:precision", "weight": 0.413},
    {"source": "measurement:tolerance", "target": "measurement:precision", "weight": 0.309},
    {"source": "measurement:density", "target": "measurement:precision", "weight": 0.489},
    {"source": "measurement:calibrate", "target": "measurement:density", "weight": 0.841},
    {"source": "measurement:count", "target": "measurement:ratio", "weight": 0.684},
    {"source": "measurement:density", "target": "measurement:gradient", "weight": 0.446},
    {"source": "measurement:margin", "target": "measurement:threshold", "weight": 0.708},
    {"source": "measurement:margin", "target": "measurement:tally", "weight": 0.828},
    {"source": "logic_code:branch", "target": "logic_code:recursion", "weight": 0.801},
    {"source": "logic_code:recursion", "target": "logic_code:truth", "weight": 0.661},
    {"source": "logic_code:truth", "target": "logic_code:function", "weight": 0.803},
    {"source": "logic_code:function", "target": "logic_code:invariant", "weight": 0.554},
    {"source": "logic_code:invariant", "target": "logic_code:null", "weight": 0.767},
    {"source": "logic_code:null", "target": "logic_code:grammar-of", "weight": 0.759},
    {"source": "logic_code:grammar-of", "target": "logic_code:entropy", "weight": 0.892},
    {"source": "logic_code:entropy", "target": "logic_code:boolean", "weight": 0.755},
    {"source": "logic_code:boolean", "target": "logic_code:syntax", "weight": 0.667},
    {"source": "logic_code:syntax", "target": "logic_code:proof", "weight": 0.812},
    {"source": "logic_code:proof", "target": "logic_code:paradox", "weight": 0.81},
    {"source": "logic_code:paradox", "target": "logic_code:cache", "weight": 0.611},
    {"source": "logic_code:cache", "target": "logic_code:stack", "weight": 0.744},
    {"source": "logic_code:stack", "target": "logic_code:pointer", "weight": 0.594},
    {"source": "logic_code:pointer", "target": "logic_code:loop", "weight": 0.668},
    {"source": "logic_code:loop", "target": "logic_code:branch", "weight": 0.731},
    {"source": "logic_code:truth", "target": "logic_code:proof", "weight": 0.793},
    {"source": "logic_code:invariant", "target": "logic_code:pointer", "weight": 0.467},
    {"source": "logic_code:cache", "target": "logic_code:branch", "weight": 0.347},
    {"source": "logic_code:proof", "target": "logic_code:cache", "weight": 0.818},
    {"source": "logic_code:branch", "target": "logic_code:function", "weight": 0.823},
    {"source": "logic_code:syntax", "target": "logic_code:invariant", "weight": 0.635},
    {"source": "logic_code:invariant", "target": "logic_code:stack", "weight": 0.429},
    {"source": "logic_code:pointer", "target": "logic_code:null", "weight": 0.732},
    {"source": "logic_code:grammar-of", "target": "logic_code:pointer", "weight": 0.521},
    {"source": "logic_code:null", "target": "logic_code:syntax", "weight": 0.79},
    {"source": "logic_code:syntax", "target": "logic_code:function", "weight": 0.572},
    {"source": "logic_code:grammar-of", "target": "logic_code:boolean", "weight": 0.343},
    {"source": "logic_code:pointer", "target": "logic_code:proof", "weight": 0.785},
    {"source": "logic_code:invariant", "target": "logic_code:entropy", "weight": 0.571},
    {"source": "logic_code:recursion", "target": "logic_code:entropy", "weight": 0.557},
    {"source": "logic_code:invariant", "target": "logic_code:paradox", "weight": 0.57},
    {"source": "logic_code:loop", "target": "logic_code:truth", "weight": 0.597},
    {"source": "logic_code:branch", "target": "logic_code:truth", "weight": 0.762},
    {"source": "logic_code:pointer", "target": "logic_code:paradox", "weight": 0.609},
    {"source": "logic_code:syntax", "target": "logic_code:stack", "weight": 0.556},
    {"source": "logic_code:stack", "target": "logic_code:grammar-of", "weight": 0.85},
    {"source": "language:syllable", "target": "language:meaning", "weight": 0.668},
    {"source": "language:meaning", "target": "language:name", "weight": 0.854},
    {"source": "language:name", "target": "language:paragraph", "weight": 0.465},
    {"source": "language:paragraph", "target": "language:story", "weight": 0.773},
    {"source": "language:story", "target": "language:whisper-word", "weight": 0.731},
    {"source": "language:whisper-word", "target": "language:grammar", "weight": 0.602},
    {"source": "language:grammar", "target": "language:idiom", "weight": 0.838},
    {"source": "language:idiom", "target": "language:question", "weight": 0.615},
    {"source": "language:question", "target": "language:metaphor", "weight": 0.664},
    {"source": "language:metaphor", "target": "language:translate", "weight": 0.686},
    {"source": "language:translate", "target": "language:stammer", "weight": 0.797},
    {"source": "language:stammer", "target": "language:silence-of", "weight": 0.545},
    {"source": "language:silence-of", "target": "language:verb", "weight": 0.646},
    {"source": "language:verb", "target": "language:accent", "weight": 0.64},
    {"source": "language:accent", "target": "language:syllable", "weight": 0.699},
    {"source": "language:verb", "target": "language:story", "weight": 0.461},
    {"source": "language:verb", "target": "language:idiom", "weight": 0.522},
    {"source": "language:question", "target": "language:story", "weight": 0.78},
    {"source": "language:whisper-word", "target": "language:paragraph", "weight": 0.66},
    {"source": "language:silence-of", "target": "language:meaning", "weight": 0.482},
    {"source": "language:whisper-word", "target": "language:stammer", "weight": 0.465},
    {"source": "language:syllable", "target": "language:grammar", "weight": 0.697},
    {"source": "language:accent", "target": "language:grammar", "weight": 0.6},
    {"source": "language:accent", "target": "language:idiom", "weight": 0.635},
    {"source": "language:translate", "target": "language:syllable", "weight": 0.734},
    {"source": "language:accent", "target": "language:question", "weight": 0.636},
    {"source": "language:metaphor", "target": "language:name", "weight": 0.645},
    {"source": "language:stammer", "target": "language:accent", "weight": 0.628},
    {"source": "language:translate", "target": "language:meaning", "weight": 0.417},
    {"source": "language:translate", "target": "language:accent", "weight": 0.552},
    {"source": "language:silence-of", "target": "language:name", "weight": 0.356},
    {"source": "language:name", "target": "language:verb", "weight": 0.32},
    {"source": "memory:childhood", "target": "memory:keepsake", "weight": 0.674},
    {"source": "memory:keepsake", "target": "memory:forgetting", "weight": 0.685},
    {"source": "memory:forgetting", "target": "memory:deja-vu", "weight": 0.821},
    {"source": "memory:deja-vu", "target": "memory:fading", "weight": 0.798},
    {"source": "memory:fading", "target": "memory:recall", "weight": 0.639},
    {"source": "memory:recall", "target": "memory:trace", "weight": 0.763},
    {"source": "memory:trace", "target": "memory:scar-of", "weight": 0.632},
    {"source": "memory:scar-of", "target": "memory:echo-of", "weight": 0.48},
    {"source": "memory:echo-of", "target": "memory:relic", "weight": 0.756},
    {"source": "memory:relic", "target": "memory:remembrance", "weight": 0.717},
    {"source": "memory:remembrance", "target": "memory:imprint", "weight": 0.897},
    {"source": "memory:imprint", "target": "memory:reminisce", "weight": 0.747},
    {"source": "memory:reminisce", "target": "memory:nostalgia", "weight": 0.52},
    {"source": "memory:nostalgia", "target": "memory:palimpsest", "weight": 0.796},
    {"source": "memory:palimpsest", "target": "memory:childhood", "weight": 0.697},
    {"source": "memory:keepsake", "target": "memory:remembrance", "weight": 0.56},
    {"source": "memory:palimpsest", "target": "memory:forgetting", "weight": 0.645},
    {"source": "memory:trace", "target": "memory:childhood", "weight": 0.305},
    {"source": "memory:nostalgia", "target": "memory:keepsake", "weight": 0.42},
    {"source": "memory:fading", "target": "memory:imprint", "weight": 0.613},
    {"source": "memory:scar-of", "target": "memory:imprint", "weight": 0.709},
    {"source": "memory:imprint", "target": "memory:palimpsest", "weight": 0.682},
    {"source": "memory:forgetting", "target": "memory:imprint", "weight": 0.718},
    {"source": "memory:fading", "target": "memory:remembrance", "weight": 0.607},
    {"source": "memory:scar-of", "target": "memory:palimpsest", "weight": 0.668},
    {"source": "memory:palimpsest", "target": "memory:fading", "weight": 0.802},
    {"source": "memory:childhood", "target": "memory:imprint", "weight": 0.318},
    {"source": "memory:remembrance", "target": "memory:nostalgia", "weight": 0.64},
    {"source": "memory:trace", "target": "memory:fading", "weight": 0.472},
    {"source": "memory:relic", "target": "memory:forgetting", "weight": 0.827},
    {"source": "memory:nostalgia", "target": "memory:scar-of", "weight": 0.635},
    {"source": "memory:recall", "target": "memory:palimpsest", "weight": 0.822},
    {"source": "emotion:longing", "target": "emotion:elation", "weight": 0.477},
    {"source": "emotion:elation", "target": "emotion:comfort", "weight": 0.888},
    {"source": "emotion:comfort", "target": "emotion:awe", "weight": 0.766},
    {"source": "emotion:awe", "target": "emotion:melancholy", "weight": 0.822},
    {"source": "emotion:melancholy", "target": "emotion:wonder", "weight": 0.599},
    {"source": "emotion:wonder", "target": "emotion:tenderness", "weight": 0.723},
    {"source": "emotion:tenderness", "target": "emotion:ache", "weight": 0.89},
    {"source": "emotion:ache", "target": "emotion:serenity", "weight": 0.824},
    {"source": "emotion:serenity", "target": "emotion:delight", "weight": 0.721},
    {"source": "emotion:delight", "target": "emotion:yearning", "weight": 0.589},
    {"source": "emotion:yearning", "target": "emotion:joy", "weight": 0.643},
    {"source": "emotion:joy", "target": "emotion:sorrow", "weight": 0.85},
    {"source": "emotion:sorrow", "target": "emotion:reverence", "weight": 0.62},
    {"source": "emotion:reverence", "target": "emotion:grief", "weight": 0.758},
    {"source": "emotion:grief", "target": "emotion:longing", "weight": 0.721},
    {"source": "emotion:grief", "target": "emotion:awe", "weight": 0.744},
    {"source": "emotion:melancholy", "target": "emotion:joy", "weight": 0.301},
    {"source": "emotion:melancholy", "target": "emotion:grief", "weight": 0.532},
    {"source": "emotion:delight", "target": "emotion:reverence", "weight": 0.72},
    {"source": "emotion:sorrow", "target": "emotion:longing", "weight": 0.459},
    {"source": "emotion:comfort", "target": "emotion:sorrow", "weight": 0.79},
    {"source": "emotion:delight", "target": "emotion:comfort", "weight": 0.451},
    {"source": "emotion:yearning", "target": "emotion:sorrow", "weight": 0.803},
    {"source": "emotion:wonder", "target": "emotion:serenity", "weight": 0.347},
    {"source": "emotion:awe", "target": "emotion:sorrow", "weight": 0.713},
    {"source": "emotion:longing", "target": "emotion:yearning", "weight": 0.518},
    {"source": "emotion:joy", "target": "emotion:awe", "weight": 0.809},
    {"source": "emotion:delight", "target": "emotion:sorrow", "weight": 0.305},
    {"source": "emotion:serenity", "target": "emotion:sorrow", "weight": 0.495},
    {"source": "emotion:elation", "target": "emotion:awe", "weight": 0.519},
    {"source": "emotion:serenity", "target": "emotion:melancholy", "weight": 0.787},
    {"source": "emotion:delight", "target": "emotion:awe", "weight": 0.404},
    {"source": "fear:foreboding", "target": "fear:helpless", "weight": 0.618},
    {"source": "fear:helpless", "target": "fear:dread", "weight": 0.498},
    {"source": "fear:dread", "target": "fear:darkness-of", "weight": 0.735},
    {"source": "fear:darkness-of", "target": "fear:startle", "weight": 0.804},
    {"source": "fear:startle", "target": "fear:cold-sweat", "weight": 0.52},
    {"source": "fear:cold-sweat", "target": "fear:flinch", "weight": 0.719},
    {"source": "fear:flinch", "target": "fear:unease", "weight": 0.605},
    {"source": "fear:unease", "target": "fear:threat", "weight": 0.684},
    {"source": "fear:threat", "target": "fear:lurking", "weight": 0.459},
    {"source": "fear:lurking", "target": "fear:nightmare", "weight": 0.465},
    {"source": "fear:nightmare", "target": "fear:vertigo", "weight": 0.896},
    {"source": "fear:vertigo", "target": "fear:trembling", "weight": 0.84},
    {"source": "fear:trembling", "target": "fear:panic", "weight": 0.669},
    {"source": "fear:panic", "target": "fear:abyss", "weight": 0.705},
    {"source": "fear:abyss", "target": "fear:foreboding", "weight": 0.568},
    {"source": "fear:trembling", "target": "fear:startle", "weight": 0.534},
    {"source": "fear:unease", "target": "fear:trembling", "weight": 0.626},
    {"source": "fear:lurking", "target": "fear:dread", "weight": 0.44},
    {"source": "fear:foreboding", "target": "fear:cold-sweat", "weight": 0.411},
    {"source": "fear:dread", "target": "fear:flinch", "weight": 0.346},
    {"source": "fear:panic", "target": "fear:vertigo", "weight": 0.552},
    {"source": "fear:panic", "target": "fear:helpless", "weight": 0.775},
    {"source": "fear:nightmare", "target": "fear:flinch", "weight": 0.807},
    {"source": "fear:vertigo", "target": "fear:helpless", "weight": 0.441},
    {"source": "fear:lurking", "target": "fear:darkness-of", "weight": 0.652},
    {"source": "fear:abyss", "target": "fear:nightmare", "weight": 0.579},
    {"source": "fear:dread", "target": "fear:unease", "weight": 0.767},
    {"source": "fear:cold-sweat", "target": "fear:darkness-of", "weight": 0.845},
    {"source": "fear:threat", "target": "fear:foreboding", "weight": 0.76},
    {"source": "fear:foreboding", "target": "fear:startle", "weight": 0.733},
    {"source": "fear:vertigo", "target": "fear:abyss", "weight": 0.656},
    {"source": "fear:unease", "target": "fear:foreboding", "weight": 0.356},
    {"source": "fear:cold-sweat", "target": "fear:trembling", "weight": 0.303},
    {"source": "fear:darkness-of", "target": "fear:nightmare", "weight": 0.712},
    {"source": "body:hunger", "target": "body:sinew", "weight": 0.557},
    {"source": "body:sinew", "target": "body:blood", "weight": 0.514},
    {"source": "body:blood", "target": "body:warmth", "weight": 0.755},
    {"source": "body:warmth", "target": "body:pulse", "weight": 0.456},
    {"source": "body:pulse", "target": "body:skin", "weight": 0.773},
    {"source": "body:skin", "target": "body:heartbeat", "weight": 0.538},
    {"source": "body:heartbeat", "target": "body:spine", "weight": 0.466},
    {"source": "body:spine", "target": "body:muscle", "weight": 0.867},
    {"source": "body:muscle", "target": "body:shiver", "weight": 0.549},
    {"source": "body:shiver", "target": "body:fingertip", "weight": 0.87},
    {"source": "body:fingertip", "target": "body:ache-of", "weight": 0.84},
    {"source": "body:ache-of", "target": "body:breath", "weight": 0.85},
    {"source": "body:breath", "target": "body:nerve", "weight": 0.513},
    {"source": "body:nerve", "target": "body:flush", "weight": 0.651},
    {"source": "body:flush", "target": "body:exhale", "weight": 0.494},
    {"source": "body:exhale", "target": "body:hunger", "weight": 0.868},
    {"source": "body:hunger", "target": "body:fingertip", "weight": 0.341},
    {"source": "body:fingertip", "target": "body:skin", "weight": 0.753},
    {"source": "body:exhale", "target": "body:sinew", "weight": 0.646},
    {"source": "body:pulse", "target": "body:spine", "weight": 0.779},
    {"source": "body:muscle", "target": "body:heartbeat", "weight": 0.526},
    {"source": "body:pulse", "target": "body:hunger", "weight": 0.449},
    {"source": "body:shiver", "target": "body:skin", "weight": 0.742},
    {"source": "body:pulse", "target": "body:muscle", "weight": 0.331},
    {"source": "body:shiver", "target": "body:sinew", "weight": 0.442},
    {"source": "body:muscle", "target": "body:warmth", "weight": 0.809},
    {"source": "body:warmth", "target": "body:heartbeat", "weight": 0.459},
    {"source": "body:skin", "target": "body:hunger", "weight": 0.758},
    {"source": "body:shiver", "target": "body:blood", "weight": 0.838},
    {"source": "body:hunger", "target": "body:spine", "weight": 0.744},
    {"source": "body:fingertip", "target": "body:muscle", "weight": 0.377},
    {"source": "body:hunger", "target": "body:breath", "weight": 0.758},
    {"source": "body:sinew", "target": "body:flush", "weight": 0.525},
    {"source": "myth:dragon", "target": "myth:prophecy", "weight": 0.543},
    {"source": "myth:prophecy", "target": "myth:oracle", "weight": 0.726},
    {"source": "myth:oracle", "target": "myth:relic-of", "weight": 0.768},
    {"source": "myth:relic-of", "target": "myth:labyrinth", "weight": 0.815},
    {"source": "myth:labyrinth", "target": "myth:angel", "weight": 0.712},
    {"source": "myth:angel", "target": "myth:phoenix", "weight": 0.541},
    {"source": "myth:phoenix", "target": "myth:chimera", "weight": 0.48},
    {"source": "myth:chimera", "target": "myth:talisman", "weight": 0.78},
    {"source": "myth:talisman", "target": "myth:threshold-god", "weight": 0.634},
    {"source": "myth:threshold-god", "target": "myth:halo-of", "weight": 0.775},
    {"source": "myth:halo-of", "target": "myth:ascension", "weight": 0.475},
    {"source": "myth:ascension", "target": "myth:omen", "weight": 0.815},
    {"source": "myth:omen", "target": "myth:leviathan", "weight": 0.601},
    {"source": "myth:leviathan", "target": "myth:underworld", "weight": 0.829},
    {"source": "myth:underworld", "target": "myth:seraph", "weight": 0.839},
    {"source": "myth:seraph", "target": "myth:dragon", "weight": 0.672},
    {"source": "myth:dragon", "target": "myth:phoenix", "weight": 0.801},
    {"source": "myth:seraph", "target": "myth:oracle", "weight": 0.78},
    {"source": "myth:talisman", "target": "myth:relic-of", "weight": 0.402},
    {"source": "myth:ascension", "target": "myth:dragon", "weight": 0.39},
    {"source": "myth:ascension", "target": "myth:threshold-god", "weight": 0.627},
    {"source": "myth:dragon", "target": "myth:angel", "weight": 0.586},
    {"source": "myth:underworld", "target": "myth:talisman", "weight": 0.339},
    {"source": "myth:ascension", "target": "myth:seraph", "weight": 0.435},
    {"source": "myth:halo-of", "target": "myth:omen", "weight": 0.691},
    {"source": "myth:omen", "target": "myth:threshold-god", "weight": 0.713},
    {"source": "myth:prophecy", "target": "myth:labyrinth", "weight": 0.78},
    {"source": "myth:seraph", "target": "myth:chimera", "weight": 0.582},
    {"source": "myth:labyrinth", "target": "myth:dragon", "weight": 0.434},
    {"source": "myth:angel", "target": "myth:prophecy", "weight": 0.472},
    {"source": "myth:phoenix", "target": "myth:labyrinth", "weight": 0.31},
    {"source": "myth:underworld", "target": "myth:prophecy", "weight": 0.493},
    {"source": "myth:relic-of", "target": "myth:ascension", "weight": 0.398},
    {"source": "myth:talisman", "target": "myth:prophecy", "weight": 0.556},
    {"source": "myth:omen", "target": "myth:underworld", "weight": 0.375},
    {"source": "myth:chimera", "target": "myth:leviathan", "weight": 0.425},
    {"source": "fear:startle", "target": "memory:nostalgia", "weight": 0.835},
    {"source": "fear:foreboding", "target": "memory:fading", "weight": 0.827},
    {"source": "fear:panic", "target": "memory:forgetting", "weight": 0.587},
    {"source": "fear:darkness-of", "target": "memory:recall", "weight": 0.648},
    {"source": "fear:nightmare", "target": "memory:imprint", "weight": 0.721},
    {"source": "light:candle", "target": "emotion:joy", "weight": 0.602},
    {"source": "light:ember", "target": "emotion:tenderness", "weight": 0.783},
    {"source": "light:flicker", "target": "emotion:serenity", "weight": 0.551},
    {"source": "light:prism", "target": "emotion:yearning", "weight": 0.557},
    {"source": "memory:palimpsest", "target": "emotion:ache", "weight": 0.728},
    {"source": "memory:relic", "target": "emotion:comfort", "weight": 0.57},
    {"source": "memory:keepsake", "target": "emotion:joy", "weight": 0.749},
    {"source": "memory:fading", "target": "emotion:delight", "weight": 0.661},
    {"source": "memory:deja-vu", "target": "emotion:reverence", "weight": 0.692},
    {"source": "sound:thunder", "target": "emotion:melancholy", "weight": 0.593},
    {"source": "sound:whisper", "target": "emotion:elation", "weight": 0.612},
    {"source": "sound:harmony", "target": "emotion:sorrow", "weight": 0.522},
    {"source": "body:shiver", "target": "fear:cold-sweat", "weight": 0.624},
    {"source": "body:heartbeat", "target": "fear:vertigo", "weight": 0.787},
    {"source": "body:muscle", "target": "fear:startle", "weight": 0.65},
    {"source": "body:heartbeat", "target": "emotion:sorrow", "weight": 0.681},
    {"source": "body:warmth", "target": "emotion:comfort", "weight": 0.552},
    {"source": "body:nerve", "target": "emotion:awe", "weight": 0.532},
    {"source": "time:clockwork", "target": "memory:deja-vu", "weight": 0.609},
    {"source": "time:yesterday", "target": "memory:forgetting", "weight": 0.454},
    {"source": "time:sudden", "target": "memory:relic", "weight": 0.474},
    {"source": "time:decay", "target": "memory:recall", "weight": 0.53},
    {"source": "myth:angel", "target": "fear:flinch", "weight": 0.691},
    {"source": "myth:oracle", "target": "fear:abyss", "weight": 0.737},
    {"source": "myth:talisman", "target": "fear:unease", "weight": 0.797},
    {"source": "myth:halo-of", "target": "light:glow", "weight": 0.469},
    {"source": "myth:prophecy", "target": "light:shimmer", "weight": 0.574},
    {"source": "myth:labyrinth", "target": "light:dawn", "weight": 0.594},
    {"source": "language:story", "target": "memory:reminisce", "weight": 0.506},
    {"source": "language:translate", "target": "memory:trace", "weight": 0.451},
    {"source": "language:question", "target": "memory:imprint", "weight": 0.48},
    {"source": "language:name", "target": "logic_code:null", "weight": 0.786},
    {"source": "language:accent", "target": "logic_code:function", "weight": 0.623},
    {"source": "language:silence-of", "target": "logic_code:truth", "weight": 0.782},
    {"source": "logic_code:truth", "target": "measurement:gradient", "weight": 0.678},
    {"source": "logic_code:loop", "target": "measurement:margin", "weight": 0.786},
    {"source": "logic_code:entropy", "target": "measurement:distance", "weight": 0.598},
    {"source": "measurement:unit", "target": "time:clockwork", "weight": 0.617},
    {"source": "measurement:density", "target": "time:instant", "weight": 0.513},
    {"source": "motion:collapse", "target": "time:yesterday", "weight": 0.536},
    {"source": "motion:drift", "target": "time:fleeting", "weight": 0.43},
    {"source": "motion:stillness", "target": "time:clockwork", "weight": 0.462},
    {"source": "motion:gesture", "target": "body:exhale", "weight": 0.714},
    {"source": "motion:orbit", "target": "body:nerve", "weight": 0.409},
    {"source": "motion:ascent", "target": "body:pulse", "weight": 0.646},
    {"source": "sound:crescendo", "target": "language:verb", "weight": 0.598},
    {"source": "sound:ringing", "target": "language:idiom", "weight": 0.48},
    {"source": "sound:harmony", "target": "language:accent", "weight": 0.574},
    {"source": "light:ember", "target": "sound:thunder", "weight": 0.455},
    {"source": "light:shimmer", "target": "sound:ringing", "weight": 0.635},
    {"source": "myth:phoenix", "target": "time:epoch", "weight": 0.45},
    {"source": "myth:underworld", "target": "time:ancient", "weight": 0.504},
    {"source": "fear:startle", "target": "emotion:joy", "weight": 0.68},
    {"source": "fear:vertigo", "target": "emotion:serenity", "weight": 0.638},
    {"source": "fear:threat", "target": "emotion:delight", "weight": 0.73},
    {"source": "light:lantern", "target": "time:ancient", "weight": 0.648},
    {"source": "light:candle", "target": "time:clockwork", "weight": 0.575},
    {"source": "body:flush", "target": "motion:sway", "weight": 0.51},
    {"source": "body:nerve", "target": "motion:plunge", "weight": 0.689},
    {"source": "emotion:tenderness", "target": "myth:leviathan", "weight": 0.699},
    {"source": "emotion:ache", "target": "myth:relic-of", "weight": 0.581},
  ]
};
