"""Installable typed clients for Clozn's gateway and native engine."""
from ._transport import (
    CloznClientError,
    CloznConnectionError,
    CloznHTTPError,
    CloznProtocolError,
)
from .engine import EngineClient
from .contracts import (
    CaptureBudget,
    CaptureStatistics,
    ContractEvidenceBinding,
    EngineProtocolAdvertisement,
    ProtocolCompatibility,
    DEFAULT_CAPTURE_BUDGET,
    ContractCheck,
    ContractReport,
    InterventionContract,
    InterventionOperation,
    MINIMAL_INTERVENTION_CONTRACT,
    OperationSpec,
    ReplayClass,
    bind_contract_evidence,
    check_contract,
    required_operations,
)
from .batch import BatchItemResult, BatchRunResult, run_manifest_batch
from .compare import BatchComparison, ExperimentComparison, MetricDelta, compare_batch_runs
from .gateway import CloznClient
from .provenance import ReproducibilityRecord, capture_reproducibility
from .reporting import (
    comparison_to_github_annotations,
    comparison_to_junit_xml,
    comparison_to_markdown,
    write_ci_reports,
)
from .manifests import (
    InterventionArm,
    InterventionArmResult,
    InterventionManifest,
    InterventionRunResult,
    ScoreRequest,
)
from .patch_manifests import PatchManifestArm, PatchSweepArtifact, PatchSweepManifest
from .models import (
    AttentionKnockout,
    HarvestResult,
    LatestRun,
    Observation,
    PatchArm,
    PatchArmResult,
    PatchSweepResult,
    ReceiptBundle,
    Run,
    RunPage,
    ScoreResult,
    ScoreToken,
    Timeline,
)

__version__ = "0.11.0"

__all__ = [
    "AttentionKnockout",
    "BatchItemResult",
    "BatchRunResult",
    "BatchComparison",
    "ExperimentComparison",
    "MetricDelta",
    "CaptureBudget",
    "CaptureStatistics",
    "ContractEvidenceBinding",
    "EngineProtocolAdvertisement",
    "ProtocolCompatibility",
    "DEFAULT_CAPTURE_BUDGET",
    "ContractCheck",
    "ContractReport",
    "InterventionContract",
    "InterventionOperation",
    "MINIMAL_INTERVENTION_CONTRACT",
    "OperationSpec",
    "ReplayClass",
    "CloznClient",
    "CloznClientError",
    "CloznConnectionError",
    "CloznHTTPError",
    "CloznProtocolError",
    "EngineClient",
    "InterventionArm",
    "InterventionArmResult",
    "InterventionManifest",
    "InterventionRunResult",
    "HarvestResult",
    "LatestRun",
    "Observation",
    "PatchArm",
    "PatchManifestArm",
    "PatchArmResult",
    "PatchSweepArtifact",
    "PatchSweepManifest",
    "PatchSweepResult",
    "ReceiptBundle",
    "ReproducibilityRecord",
    "Run",
    "RunPage",
    "ScoreRequest",
    "ScoreResult",
    "ScoreToken",
    "Timeline",
    "run_manifest_batch",
    "compare_batch_runs",
    "comparison_to_github_annotations",
    "comparison_to_junit_xml",
    "comparison_to_markdown",
    "write_ci_reports",
    "capture_reproducibility",
    "bind_contract_evidence",
    "check_contract",
    "required_operations",
    "__version__",
]
