"""Shared test fixtures and the golden-oracle contract.

Golden tests pin seeded (prompt, seed, policy) -> exact token picks with
confidences within epsilon (DESIGN invariant 3): never assert bitwise
equality on float sums, since reduction order differs across devices. The
machinery lives in ``cloze_lab.golden``; fixtures are JSON under ``golden/``,
regenerated by ``golden/_generate.py``.
"""

from pathlib import Path

import pytest

GOLDEN_DIR = Path(__file__).parent / "golden"


@pytest.fixture(scope="session")
def golden_dir() -> Path:
    return GOLDEN_DIR
