"""Tone and behavior steering axis definitions."""
from __future__ import annotations

# Each axis: a + pole and a - pole, expressed as system instructions. The steering vector is
# mean(resid | +pole) - mean(resid | -pole) over a few neutral seed prompts, isolating tone
# from content. Slider value scales it: + = toward the first pole, - = toward the second.
AXES = {
    "warm":    {"pos": "Respond in a warm, caring, encouraging tone.",
                "neg": "Respond in a cold, detached, clinical tone.",          "poles": ("warm", "detached")},
    "concise": {"pos": "Respond extremely concisely, in one short sentence.",
                "neg": "Respond at great length, with elaborate detail.",       "poles": ("concise", "verbose")},
    "formal":  {"pos": "Respond in very formal, professional language.",
                "neg": "Respond in very casual, slangy, relaxed language.",     "poles": ("formal", "casual")},
    "playful": {"pos": "Respond in a playful, witty, lighthearted tone.",
                "neg": "Respond in a serious, sober, no-nonsense tone.",        "poles": ("playful", "serious")},
    "curious": {"pos": "Respond with curiosity, wondering aloud and asking thoughtful questions.",
                "neg": "Respond flatly, just stating facts with no curiosity.",  "poles": ("curious", "matter-of-fact")},
    "poetic":  {"pos": "Respond poetically, with vivid imagery and metaphor.",
                "neg": "Respond plainly and literally, with no figurative language.", "poles": ("poetic", "plain")},
    "technical": {"pos": "Respond technically, with precise terminology and detail.",
                  "neg": "Respond in simple, everyday language anyone could follow.", "poles": ("technical", "simple")},
    # Cognitive / behavioral axes are finickier than tone and carry calibrated safe max strengths.
    "candid":  {"pos": "Respond with candid, critical pushback: point out flaws and disagree when it is warranted, do not just validate.",
                "neg": "Respond agreeably and supportively: validate the user's view and avoid disagreement.", "poles": ("candid", "agreeable"), "max": 0.45},
    "confident": {"pos": "Respond with confident, decisive assertions and no hedging.",
                  "neg": "Respond cautiously and tentatively, hedging with qualifications and uncertainty.", "poles": ("confident", "tentative"), "max": 1.0},
    "concrete": {"pos": "Respond with concrete, specific detail and vivid, particular examples.",
                 "neg": "Respond abstractly, in general high-level concepts with no specifics.", "poles": ("concrete", "abstract"), "max": 0.5},
}


# STYLE preference lexicon: style/tone phrases -> (axis, sign). sign +1 means the axis's first
# pole; sign -1 means the second. Entries are explicit so inflections are auditable and do not
# over-match unrelated words.
_DIAL_LEXICON: list[tuple[str, str, int]] = [
    ("concise", "concise", +1), ("brief", "concise", +1), ("briefer", "concise", +1),
    ("briefly", "concise", +1),
    ("short", "concise", +1), ("shorter", "concise", +1), ("shortest", "concise", +1),
    ("terse", "concise", +1), ("terser", "concise", +1),
    ("succinct", "concise", +1), ("to the point", "concise", +1), ("no fluff", "concise", +1),
    ("no filler", "concise", +1), ("get to the point", "concise", +1), ("tl;dr", "concise", +1),
    ("verbose", "concise", -1), ("detailed", "concise", -1), ("more detail", "concise", -1),
    ("elaborate", "concise", -1), ("thorough", "concise", -1), ("in depth", "concise", -1),
    ("in-depth", "concise", -1), ("long", "concise", -1), ("longer", "concise", -1),
    ("longest", "concise", -1), ("lengthy", "concise", -1), ("lengthier", "concise", -1),
    ("comprehensive", "concise", -1), ("expansive", "concise", -1),
    ("formal", "formal", +1), ("formally", "formal", +1), ("professional", "formal", +1),
    ("professionally", "formal", +1), ("polished", "formal", +1),
    ("businesslike", "formal", +1), ("proper", "formal", +1),
    ("casual", "formal", -1), ("informal", "formal", -1), ("relaxed", "formal", -1),
    ("laid-back", "formal", -1), ("laid back", "formal", -1), ("chill", "formal", -1),
    ("conversational", "formal", -1), ("colloquial", "formal", -1), ("slangy", "formal", -1),
    ("warm", "warm", +1), ("warmer", "warm", +1), ("warmest", "warm", +1),
    ("warmhearted", "warm", +1), ("warm-hearted", "warm", +1),
    ("kind", "warm", +1), ("kinder", "warm", +1), ("kindest", "warm", +1),
    ("caring", "warm", +1), ("compassionate", "warm", +1),
    ("friendly", "warm", +1), ("friendlier", "warm", +1), ("friendliest", "warm", +1),
    ("gentle", "warm", +1), ("gentler", "warm", +1), ("empathetic", "warm", +1),
    ("supportive", "warm", +1), ("encouraging", "warm", +1), ("nurturing", "warm", +1),
    ("calm", "warm", +1), ("calmer", "warm", +1),
    ("cold", "warm", -1), ("colder", "warm", -1), ("detached", "warm", -1), ("neutral", "warm", -1),
    ("clinical", "warm", -1), ("impersonal", "warm", -1), ("distant", "warm", -1),
    ("aloof", "warm", -1),
    ("technical", "technical", +1), ("precise", "technical", +1), ("jargon", "technical", +1),
    ("rigorous", "technical", +1), ("specialized", "technical", +1),
    ("simple", "technical", -1), ("simpler", "technical", -1), ("simplest", "technical", -1),
    ("plain", "technical", -1), ("plainer", "technical", -1), ("plainly", "technical", -1),
    ("plain english", "technical", -1), ("plain language", "technical", -1),
    ("layman", "technical", -1), ("layman's terms", "technical", -1), ("laymans terms", "technical", -1),
    ("no jargon", "technical", -1), ("beginner-friendly", "technical", -1),
    ("beginner friendly", "technical", -1), ("accessible", "technical", -1),
    ("everyday language", "technical", -1),
    ("playful", "playful", +1), ("fun", "playful", +1), ("humor", "playful", +1),
    ("humorous", "playful", +1), ("witty", "playful", +1), ("wittier", "playful", +1),
    ("wit", "playful", +1),
    ("funny", "playful", +1), ("funnier", "playful", +1), ("lighthearted", "playful", +1),
    ("light-hearted", "playful", +1),
    ("whimsical", "playful", +1), ("jokes", "playful", +1),
    ("serious", "playful", -1), ("dry", "playful", -1), ("drier", "playful", -1),
    ("dryer", "playful", -1), ("sober", "playful", -1),
    ("no-nonsense", "playful", -1), ("no nonsense", "playful", -1), ("solemn", "playful", -1),
    ("earnest", "playful", -1),
    ("curious", "curious", +1), ("inquisitive", "curious", +1), ("wondering", "curious", +1),
    ("exploratory", "curious", +1),
    ("matter-of-fact", "curious", -1), ("matter of fact", "curious", -1),
    ("just the facts", "curious", -1), ("just state facts", "curious", -1),
    ("poetic", "poetic", +1), ("lyrical", "poetic", +1), ("figurative", "poetic", +1),
    ("metaphor", "poetic", +1), ("metaphorical", "poetic", +1), ("imagery", "poetic", +1),
    ("evocative", "poetic", +1),
    ("literal", "poetic", -1), ("prosaic", "poetic", -1), ("no metaphor", "poetic", -1),
    ("no metaphors", "poetic", -1),
    ("candid", "candid", +1), ("blunt", "candid", +1), ("blunter", "candid", +1),
    ("bluntly", "candid", +1),
    ("frank", "candid", +1), ("direct", "candid", +1), ("straightforward", "candid", +1),
    ("honest", "candid", +1), ("critical", "candid", +1), ("pushback", "candid", +1),
    ("push back", "candid", +1), ("no sugarcoating", "candid", +1),
    ("dont sugarcoat", "candid", +1), ("don't sugarcoat", "candid", +1),
    ("agreeable", "candid", -1), ("supportive of my view", "candid", -1),
    ("validating", "candid", -1), ("affirming", "candid", -1), ("dont disagree", "candid", -1),
    ("don't disagree", "candid", -1),
    ("confident", "confident", +1), ("decisive", "confident", +1), ("assertive", "confident", +1),
    ("no hedging", "confident", +1), ("dont hedge", "confident", +1), ("don't hedge", "confident", +1),
    ("definitive", "confident", +1),
    ("tentative", "confident", -1), ("hedged", "confident", -1), ("cautious", "confident", -1),
    ("hedge", "confident", -1), ("uncertain", "confident", -1), ("qualified", "confident", -1),
    ("nuanced caveats", "confident", -1),
    ("concrete", "concrete", +1), ("specific", "concrete", +1), ("with examples", "concrete", +1),
    ("give examples", "concrete", +1), ("particular", "concrete", +1), ("tangible", "concrete", +1),
    ("abstract", "concrete", -1), ("high-level", "concrete", -1), ("high level", "concrete", -1),
    ("conceptual", "concrete", -1), ("theoretical", "concrete", -1), ("general", "concrete", -1),
]

_DIAL_DEFAULT_MAG = 0.6
_DIAL_REDUCERS = ("less", "not", "no", "n't", "too", "overly", "avoid", "avoids", "stop", "without")


# Neutral user turns to elicit the contrast on. Varied so the averaged direction captures tone, not
# any one topic.
SEED_PROMPTS = [
    "Tell me about your weekend plans.",
    "Can you help me with a problem at work?",
    "What do you think about this idea I have?",
    "Give me some advice for today.",
    "Explain what you can help with.",
    "I just got back from a trip.",
    "I'm trying to decide between two job offers.",
    "Why is the sky blue?",
    "I had a rough day and just need to vent.",
    "What's a good book to read this month?",
    "Walk me through how to set up a budget.",
    "My friend and I had a disagreement yesterday.",
    "I'm thinking about picking up a new hobby.",
    "Summarize what's been going on in the news.",
    "Honestly, is it worth learning to cook?",
    "Tell me something interesting.",
    "I keep procrastinating on a big project.",
    "What should I make for dinner tonight?",
]
