"""Builds the plain nbformat-v4 ``reproduce.ipynb`` written into every ``clozn runs export-bundle``
directory (roadmap Phase 4.5 "Open export") -- by hand, as a JSON object. No ``nbformat``/``jupyter``
dependency is involved in either generating or reading it; both this module and the notebook's own code
cells only ever need the standard library (plus NumPy, optionally, inside the notebook itself).

Design rule that keeps this safe: every code cell below loads its data FRESH, at notebook-run time, from
``manifest.json``/``receipt_bundle.json``/``influence_map.json`` sitting next to it in the bundle
directory. No run-derived string (a prompt, a model name, a run id, ...) is ever interpolated directly
into a code cell's SOURCE at generation time -- only fixed, hand-written boilerplate is. That sidesteps
the otherwise-real risk of an adversarial run field (say, a prompt containing a stray triple-quote
sequence, or an embedded backslash sequence) corrupting the generated Python source, or worse. Markdown
cells DO quote a few manifest fields verbatim for a readable title/summary; markdown is never executed,
so that carries no such risk.

Network policy for the generated notebook (distinct from THIS module, which never touches the network):
every cell is offline-only EXCEPT the one, clearly labeled "OPTIONAL" reproduction cell, which -- only if
the user chooses to run it, and only if an engine answers on ENGINE_URL -- POSTs the recorded prompt/
continuation to ``/score`` using stdlib ``urllib.request`` and compares the returned ``sum_logprob``
against whatever recorded baseline the bundle has. That is the ONE live-reproducibility claim this whole
feature makes, and it is never treated as proven unless that request actually succeeds against a
model_sha256-matching engine.
"""
from __future__ import annotations

NBFORMAT = 4
NBFORMAT_MINOR = 5


def _lines(text: str) -> "list[str]":
    """nbformat cell ``source`` convention: a list of lines, each keeping its own trailing newline
    except the very last line of the cell."""
    if not text:
        return [""]
    rows = text.splitlines(keepends=True)
    return rows if rows else [""]


def _markdown_cell(text: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": _lines(text.strip("\n"))}


def _code_cell(text: str) -> dict:
    return {
        "cell_type": "code", "metadata": {}, "execution_count": None, "outputs": [],
        "source": _lines(text.strip("\n") + "\n"),
    }


def _intro_markdown(manifest: dict, receipt: "dict | None") -> str:
    run = (receipt or {}).get("run") or {}
    honesty = manifest.get("honesty") or {}
    lines = [
        f"# Reproduction notebook -- run `{manifest.get('run_id')}`",
        "",
        f"Generated by `clozn runs export-bundle` ({manifest.get('generated_at')}, "
        f"clozn {manifest.get('clozn_version')}).",
    ]
    model = run.get("model")
    if model:
        lines.append(f"Model: `{model}`")
    method = manifest.get("method")
    if isinstance(method, dict) and method.get("name"):
        lines.append(f"Influence-map method: `{method['name']}`")
    scope = manifest.get("scope")
    if scope:
        lines.append(f"Prompt scope considered: `{scope}`")
    lines += [
        "",
        "## What this notebook can and cannot prove",
        "",
        str(honesty.get("note") or "See manifest.json's 'honesty' block."),
        "",
        "This notebook runs top to bottom with **only the standard library, plus NumPy if you have it "
        "installed** (only used for the optional tensor cell) -- no `clozn` or `clozn-client` install "
        "required. Only the LAST code cell touches the network, and only if you choose to run it.",
    ]
    return "\n".join(lines)


def _setup_cell() -> str:
    return (
        "import hashlib\n"
        "import json\n"
        "from pathlib import Path\n"
        "\n"
        "try:\n"
        "    import numpy as np\n"
        "    HAVE_NUMPY = True\n"
        "except ImportError:\n"
        "    HAVE_NUMPY = False\n"
        "\n"
        "# This notebook is written to live INSIDE the bundle directory `clozn runs export-bundle`\n"
        "# produced. If you moved reproduce.ipynb somewhere else, point BUNDLE_DIR at the bundle\n"
        "# directory instead.\n"
        "BUNDLE_DIR = Path('.')\n"
        "\n"
        "with open(BUNDLE_DIR / 'manifest.json', 'r', encoding='utf-8') as _fh:\n"
        "    manifest = json.load(_fh)\n"
        "\n"
        "print(f\"bundle for run {manifest['run_id']!r}\")\n"
        "print(f\"schema: {manifest['schema']!r}  generated_at: {manifest['generated_at']}\")\n"
        "print(f\"identity: {manifest.get('identity')}\")\n"
    )


def _verify_markdown() -> str:
    return (
        "## Step 1 -- hash-verify every artifact, fully offline\n\n"
        "Every file `manifest.json` lists under `artifacts` has a recorded SHA-256. Re-hashing them here "
        "and comparing is the ONE thing this notebook can prove with total confidence: whether the bytes "
        "you have on disk are exactly the bytes this bundle was built from. It proves nothing about "
        "whether the ORIGINAL run/receipt itself was correct -- only that this copy of it is intact."
    )


def _verify_cell() -> str:
    return (
        "def _sha256_file(path, chunk_size=1 << 20):\n"
        "    digest = hashlib.sha256()\n"
        "    with open(path, 'rb') as fh:\n"
        "        while True:\n"
        "            chunk = fh.read(chunk_size)\n"
        "            if not chunk:\n"
        "                break\n"
        "            digest.update(chunk)\n"
        "    return digest.hexdigest()\n"
        "\n"
        "verification = []\n"
        "for artifact in manifest['artifacts']:\n"
        "    path = BUNDLE_DIR / artifact['path']\n"
        "    if not path.is_file():\n"
        "        verification.append((artifact['path'], 'MISSING'))\n"
        "        continue\n"
        "    actual = _sha256_file(path)\n"
        "    ok = actual == artifact['sha256']\n"
        "    verification.append((artifact['path'], 'OK' if ok else 'TAMPERED'))\n"
        "\n"
        "for path, status in verification:\n"
        "    print(f'{status:<8} {path}')\n"
        "\n"
        "_bad = [row for row in verification if row[1] != 'OK']\n"
        "if _bad:\n"
        "    print(f\"\\nWARNING: {len(_bad)} artifact(s) failed hash verification -- treat this \"\n"
        "          f\"bundle's evidence as UNVERIFIED until this is resolved.\")\n"
        "else:\n"
        "    print(f'\\nAll {len(verification)} artifact(s) hash-verified offline against manifest.json.')\n"
    )


def _receipt_markdown() -> str:
    return "## Step 2 -- reconstruct the receipt tables"


def _receipt_cell() -> str:
    return (
        "receipt_path = BUNDLE_DIR / 'receipt_bundle.json'\n"
        "receipt = json.loads(receipt_path.read_text(encoding='utf-8')) if receipt_path.is_file() "
        "else None\n"
        "\n"
        "if receipt is not None:\n"
        "    run = receipt.get('run') or {}\n"
        "    identity = receipt.get('identity') or {}\n"
        "    print('run id:      ', run.get('id'))\n"
        "    print('model:       ', run.get('model'))\n"
        "    print('source:      ', run.get('source'), '/', run.get('client'))\n"
        "    print('finish:      ', run.get('finish_reason'))\n"
        "    print('model_sha256:', identity.get('model_sha256'))\n"
        "    print()\n"
        "    for message in (run.get('messages') or []):\n"
        "        if isinstance(message, dict):\n"
        "            print(f\"[{message.get('role', '?')}] {str(message.get('content', ''))[:500]}\")\n"
        "    if run.get('response'):\n"
        "        print(f\"[assistant] {str(run['response'])[:500]}\")\n"
        "else:\n"
        "    print('receipt_bundle.json not found in this bundle directory.')\n"
        "\n"
        "influence_path = BUNDLE_DIR / 'influence_map.json'\n"
        "if influence_path.is_file():\n"
        "    influence_map = json.loads(influence_path.read_text(encoding='utf-8'))\n"
        "    method = influence_map.get('method') or {}\n"
        "    print('\\n## context -> answer influence map')\n"
        "    print('method:      ', method.get('name'))\n"
        "    print('claim_limit: ', method.get('claim_limit'))\n"
        "    links = influence_map.get('links') or []\n"
        "    print(f'{len(links)} link(s) recorded')\n"
        "    for link in links[:20]:\n"
        "        print(' -', link)\n"
        "else:\n"
        "    influence_map = None\n"
        "    print('\\nno influence_map.json in this bundle (no context<->answer map was computed for '\n"
        "          'this run)')\n"
    )


def _tensors_markdown() -> str:
    return (
        "## Step 3 -- load the exported tensors (optional, needs NumPy for the .npz form)\n\n"
        "`tensors.npz` (NumPy available at export time) or one `<name>.f32.bin` file per array "
        "(fallback) -- either way, the exact shape/dtype of each array is in `manifest.json`."
    )


def _tensors_cell() -> str:
    return (
        "tensor_entries = [a for a in manifest['artifacts'] if a.get('kind') == 'tensor_payload']\n"
        "arrays = {}\n"
        "if not tensor_entries:\n"
        "    print('no tensor payload in this bundle.')\n"
        "elif tensor_entries[0].get('format') == 'npz':\n"
        "    if HAVE_NUMPY:\n"
        "        with np.load(BUNDLE_DIR / tensor_entries[0]['path']) as archive:\n"
        "            arrays = {name: archive[name] for name in archive.files}\n"
        "        for name, arr in arrays.items():\n"
        "            print(f'{name}: shape={arr.shape} dtype={arr.dtype}')\n"
        "    else:\n"
        "        print('tensors.npz is present but NumPy is not installed here -- install numpy to '\n"
        "              'read it (`pip install numpy`), or re-export the bundle without NumPy available '\n"
        "              'to get the raw .bin fallback instead.')\n"
        "else:\n"
        "    import struct\n"
        "    for entry in tensor_entries:\n"
        "        path = BUNDLE_DIR / entry['path']\n"
        "        raw = path.read_bytes()\n"
        "        count = len(raw) // 4\n"
        "        flat = struct.unpack(f'<{count}f', raw)\n"
        "        arrays[entry['array_name']] = flat\n"
        "        print(f\"{entry['array_name']}: shape={entry['shape']} dtype=float32 \"\n"
        "              f\"(read via struct, no NumPy)\")\n"
    )


def _reproduction_markdown(manifest: dict) -> str:
    live = (manifest.get("honesty") or {}).get("live_reproduction") or {}
    requires = live.get("requires") or []
    bullet_list = "\n".join(f"- {item}" for item in requires)
    return (
        "## Step 4 -- OPTIONAL live reproducibility check\n\n"
        "**This is the only cell in this notebook that uses the network, and only runs the request if "
        "you execute it.** Nothing above this point needed anything but the files already in this "
        "bundle directory.\n\n"
        f"Claim under test: `{live.get('claim', 'n/a')}`. This requires:\n\n"
        f"{bullet_list}\n\n"
        "If the engine isn't reachable, or doesn't report the same `model_sha256`, or this run has no "
        "exact recorded prompt/response to replay, the cell below explains why and skips -- it never "
        "reports a verdict it cannot actually support."
    )


def _reproduction_cell() -> str:
    return (
        "import urllib.error\n"
        "import urllib.request\n"
        "\n"
        "# EDIT THIS if your engine is not on the default local port.\n"
        "ENGINE_URL = manifest.get('engine_url') or 'http://127.0.0.1:8091'\n"
        "\n"
        "def _get_json(url, timeout=1.5):\n"
        "    try:\n"
        "        with urllib.request.urlopen(url, timeout=timeout) as response:\n"
        "            return json.loads(response.read().decode('utf-8'))\n"
        "    except Exception:\n"
        "        return None\n"
        "\n"
        "def _post_json(url, body, timeout=120.0):\n"
        "    data = json.dumps(body).encode('utf-8')\n"
        "    request = urllib.request.Request(\n"
        "        url, data=data, headers={'Content-Type': 'application/json'}, method='POST')\n"
        "    with urllib.request.urlopen(request, timeout=timeout) as response:\n"
        "        return json.loads(response.read().decode('utf-8'))\n"
        "\n"
        "print('OPTIONAL reproducibility check against', ENGINE_URL)\n"
        "health = _get_json(ENGINE_URL.rstrip('/') + '/health')\n"
        "\n"
        "if health is None:\n"
        "    print(f'no engine reachable at {ENGINE_URL} -- skipping. Nothing above this point '\n"
        "          f'required the network; every hash check already ran fully offline.')\n"
        "elif receipt is None:\n"
        "    print('no receipt_bundle.json loaded -- skipping (need the recorded prompt/response).')\n"
        "else:\n"
        "    recorded_sha = (receipt.get('identity') or {}).get('model_sha256')\n"
        "    health_model = health.get('model')\n"
        "    live_sha = health_model.get('sha256') if isinstance(health_model, dict) else None\n"
        "    if recorded_sha and live_sha and recorded_sha != live_sha:\n"
        "        print(f'engine at {ENGINE_URL} is serving a DIFFERENT model '\n"
        "              f'(sha256 {live_sha} != recorded {recorded_sha}) -- a score from it would not '\n"
        "              f'be a reproduction of this receipt. Skipping.')\n"
        "    else:\n"
        "        run = receipt.get('run') or {}\n"
        "        prompt = run.get('final_prompt')\n"
        "        continuation = run.get('response')\n"
        "        if not isinstance(prompt, str) or not prompt \\\n"
        "                or not isinstance(continuation, str) or not continuation:\n"
        "            print('this run has no exact rendered prompt + response recorded -- cannot '\n"
        "                  'replay a teacher-forced score. Skipping.')\n"
        "        else:\n"
        "            try:\n"
        "                score = _post_json(ENGINE_URL.rstrip('/') + '/score',\n"
        "                                   {'prompt': prompt, 'continuation': continuation, 'topk': 0})\n"
        "            except Exception as exc:\n"
        "                print(f'live score request failed ({type(exc).__name__}: {exc}) -- skipping.')\n"
        "                score = None\n"
        "            if score is not None:\n"
        "                live_sum = score.get('sum_logprob')\n"
        "                recorded_sum = None\n"
        "                if influence_map is not None:\n"
        "                    logprobs = (influence_map.get('baseline') or {}).get('logprobs')\n"
        "                    if isinstance(logprobs, list) and logprobs:\n"
        "                        recorded_sum = sum(logprobs)\n"
        "                if recorded_sum is None:\n"
        "                    print(f'live sum_logprob = {live_sum!r} (no recorded baseline logprob '\n"
        "                          f'sum in this bundle to compare against -- printed for inspection '\n"
        "                          f'only, not a verdict).')\n"
        "                else:\n"
        "                    delta = abs(live_sum - recorded_sum)\n"
        "                    tolerance = 0.05 * max(1.0, abs(recorded_sum))\n"
        "                    verdict = ('REPRODUCED (within tolerance)' if delta <= tolerance else\n"
        "                               'DIVERGED (outside tolerance -- could be a different '\n"
        "                               'build/quantization/sampler path, or genuine drift)')\n"
        "                    print(f'recorded sum_logprob: {recorded_sum!r}')\n"
        "                    print(f'live     sum_logprob: {live_sum!r}')\n"
        "                    print(f'|delta| = {delta!r}  (tolerance {tolerance!r})')\n"
        "                    print(f'verdict: {verdict}')\n"
    )


def _closing_markdown() -> str:
    return (
        "---\n\n"
        "**Recap:** the hash-verification cell above is the only claim this notebook can make with "
        "certainty on its own -- that the files in this directory are exactly what the bundle was built "
        "from. Everything under `## context -> answer influence map` and the receipt tables is HASH-"
        "VERIFIED EVIDENCE, not independently re-derived. The live reproduction cell, if run "
        "successfully against a matching engine, is the only check in this notebook that re-computes "
        "anything rather than just reading it back."
    )


def build_reproduction_notebook(manifest: dict, receipt: "dict | None" = None) -> dict:
    """Return the complete nbformat-v4 notebook object (JSON-serializable) for one export bundle.

    Pure function of already-computed data: never touches disk, the network, or `clozn.runs.store`.
    """
    cells = [
        _markdown_cell(_intro_markdown(manifest, receipt)),
        _code_cell(_setup_cell()),
        _markdown_cell(_verify_markdown()),
        _code_cell(_verify_cell()),
        _markdown_cell(_receipt_markdown()),
        _code_cell(_receipt_cell()),
        _markdown_cell(_tensors_markdown()),
        _code_cell(_tensors_cell()),
        _markdown_cell(_reproduction_markdown(manifest)),
        _code_cell(_reproduction_cell()),
        _markdown_cell(_closing_markdown()),
    ]
    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "pygments_lexer": "ipython3"},
            "clozn": {"schema": "clozn.export_bundle.v1", "run_id": manifest.get("run_id")},
        },
        "nbformat": NBFORMAT,
        "nbformat_minor": NBFORMAT_MINOR,
    }


__all__ = ["build_reproduction_notebook"]
